
package Vista;

import java.awt.Color;

public class vistaHerramienta extends javax.swing.JFrame {

    public vistaHerramienta() {
         setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        initComponents();
        //setIconImage(getIconImage());
        
    }
/*Icono del proyecyo
    @Override
    public Image getIconImage (){
        String ruta = System.getProperty("user.dir");
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource(ruta+"/src/main/resources/img/mini.jpg"));
        return retValue;}*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redondear1 = new Modelo.Redondear();
        jdpEscritorio = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        redondear2 = new Modelo.Redondear();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        redondear3 = new Modelo.Redondear();
        jLabel3 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVentas = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnInventario = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnTrabajadores = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnHistorial = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEditoriales = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 670));

        redondear1.setBackground(new java.awt.Color(240, 244, 239));
        redondear1.setPreferredSize(new java.awt.Dimension(1500, 660));
        redondear1.setRoundBottomLeft(60);
        redondear1.setRoundBottomRight(60);
        redondear1.setRoundTopLeft(60);
        redondear1.setRoundTopRight(60);
        redondear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdpEscritorio.setBackground(new java.awt.Color(240, 244, 239));
        jdpEscritorio.setRequestFocusEnabled(false);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\logo.jpg")); // NOI18N
        jLabel7.setText("jLabel7");

        jdpEscritorio.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpEscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpEscritorioLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        redondear1.add(jdpEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 870, 580));

        redondear2.setBackground(new java.awt.Color(242, 60, 39));
        redondear2.setRoundBottomLeft(60);
        redondear2.setRoundTopLeft(60);
        redondear2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 210, 129));
        jLabel1.setText("Panel De");
        redondear2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 170, 35));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 210, 129));
        jLabel2.setText("Herramientas");
        redondear2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 35));

        redondear3.setBackground(new java.awt.Color(247, 210, 129));
        redondear3.setRoundBottomLeft(60);
        redondear3.setRoundBottomRight(60);
        redondear3.setRoundTopLeft(60);
        redondear3.setRoundTopRight(60);
        redondear3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bienvenido,");
        redondear3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 90, 30));
        redondear3.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 70, 60));

        lblNombres.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(0, 0, 0));
        lblNombres.setText("Diego");
        redondear3.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 20));

        lblApellidos.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidos.setText("Bautista");
        redondear3.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, 20));

        lblDNI.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(0, 0, 0));
        lblDNI.setText("DNI:75792854");
        redondear3.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\informacion (1).png")); // NOI18N
        jLabel5.setText("jLabel5");
        redondear3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 37, -1));

        redondear2.add(redondear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 230, 110));

        btnVentas.setBackground(new java.awt.Color(242, 60, 39));
        btnVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(247, 210, 129));
        jLabel10.setText("Ventas");
        btnVentas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\ventas.png")); // NOI18N
        btnVentas.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        redondear2.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, 70));

        btnInventario.setBackground(new java.awt.Color(242, 60, 39));
        btnInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(247, 210, 129));
        jLabel8.setText("Inventario");
        btnInventario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\libro-comico.png")); // NOI18N
        btnInventario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        redondear2.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 70));

        btnTrabajadores.setBackground(new java.awt.Color(242, 60, 39));
        btnTrabajadores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(247, 210, 129));
        jLabel12.setText("Trabajadores");
        btnTrabajadores.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\superheroe.png")); // NOI18N
        btnTrabajadores.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        redondear2.add(btnTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 70));

        btnHistorial.setBackground(new java.awt.Color(242, 60, 39));
        btnHistorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\historial-medico.png")); // NOI18N
        btnHistorial.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(247, 210, 129));
        jLabel14.setText("Historial");
        btnHistorial.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, -1));

        redondear2.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 250, 70));

        btnEditoriales.setBackground(new java.awt.Color(242, 60, 39));
        btnEditoriales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(247, 210, 129));
        jLabel16.setText("Editoriales");
        btnEditoriales.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\libro-comico_1.png")); // NOI18N
        btnEditoriales.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        redondear2.add(btnEditoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 70));

        redondear1.add(redondear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 650));

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        redondear1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 37, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        redondear1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 37, -1));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\fuerza.png")); // NOI18N
        redondear1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redondear1, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(redondear1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaHerramienta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnCerrarSesion;
    public javax.swing.JPanel btnEditoriales;
    public javax.swing.JPanel btnHistorial;
    public javax.swing.JPanel btnInventario;
    public javax.swing.JPanel btnTrabajadores;
    public javax.swing.JPanel btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JDesktopPane jdpEscritorio;
    public javax.swing.JLabel lblApellidos;
    public javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblDNI;
    public javax.swing.JLabel lblFoto;
    public javax.swing.JLabel lblMinimizar;
    public javax.swing.JLabel lblNombres;
    private Modelo.Redondear redondear1;
    private Modelo.Redondear redondear2;
    private Modelo.Redondear redondear3;
    // End of variables declaration//GEN-END:variables
}
