/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author Frank
 */
public class vistaHerramienta extends javax.swing.JFrame {

    /**
     * Creates new form vistaHerramienta
     */
    public vistaHerramienta() {
         setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        initComponents();
        setLocationRelativeTo(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redondear1 = new Modelo.Redondear();
        jdpEscritorio = new javax.swing.JDesktopPane();
        redondear2 = new Modelo.Redondear();
        jLabel1 = new javax.swing.JLabel();
        btnVentas = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        bntHistorial = new javax.swing.JButton();
        btnEditoriales = new javax.swing.JButton();
        btnTrabajadores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        redondear3 = new Modelo.Redondear();
        jLabel3 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        btnCerrarSesion = new Modelo.Redondear();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 670));

        redondear1.setBackground(new java.awt.Color(240, 244, 239));
        redondear1.setPreferredSize(new java.awt.Dimension(1500, 660));
        redondear1.setRoundBottomLeft(60);
        redondear1.setRoundBottomRight(60);
        redondear1.setRoundTopLeft(60);
        redondear1.setRoundTopRight(60);
        redondear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdpEscritorio.setBackground(new java.awt.Color(240, 244, 239));
        jdpEscritorio.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        redondear1.add(jdpEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 870, 580));

        redondear2.setBackground(new java.awt.Color(191, 204, 148));
        redondear2.setRoundBottomLeft(60);
        redondear2.setRoundTopLeft(60);
        redondear2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Panel De");
        redondear2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 35));

        btnVentas.setBackground(new java.awt.Color(191, 204, 148));
        btnVentas.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnVentas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\carrito-de-compras (2).png")); // NOI18N
        btnVentas.setText("      Ventas");
        btnVentas.setBorder(null);
        redondear2.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 70));

        btnInventario.setBackground(new java.awt.Color(191, 204, 148));
        btnInventario.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(0, 0, 0));
        btnInventario.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\alt-de-inventario.png")); // NOI18N
        btnInventario.setText("  Inventario");
        btnInventario.setBorder(null);
        redondear2.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 70));

        bntHistorial.setBackground(new java.awt.Color(191, 204, 148));
        bntHistorial.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        bntHistorial.setForeground(new java.awt.Color(0, 0, 0));
        bntHistorial.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\lista.png")); // NOI18N
        bntHistorial.setText("    Historial");
        bntHistorial.setBorder(null);
        bntHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntHistorialActionPerformed(evt);
            }
        });
        redondear2.add(bntHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 270, 70));

        btnEditoriales.setBackground(new java.awt.Color(191, 204, 148));
        btnEditoriales.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnEditoriales.setForeground(new java.awt.Color(0, 0, 0));
        btnEditoriales.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\editar.png")); // NOI18N
        btnEditoriales.setText("Editoriales");
        btnEditoriales.setBorder(null);
        btnEditoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialesActionPerformed(evt);
            }
        });
        redondear2.add(btnEditoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 270, 70));

        btnTrabajadores.setBackground(new java.awt.Color(191, 204, 148));
        btnTrabajadores.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnTrabajadores.setForeground(new java.awt.Color(0, 0, 0));
        btnTrabajadores.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\usuarios (1).png")); // NOI18N
        btnTrabajadores.setText("  Trabajadores");
        btnTrabajadores.setBorder(null);
        btnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadoresActionPerformed(evt);
            }
        });
        redondear2.add(btnTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 270, 70));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Herramientas");
        redondear2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 35));

        redondear3.setBackground(new java.awt.Color(143, 153, 111));
        redondear3.setRoundBottomLeft(60);
        redondear3.setRoundBottomRight(60);
        redondear3.setRoundTopLeft(60);
        redondear3.setRoundTopRight(60);
        redondear3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bienvenido,");
        redondear3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, 90, 30));
        redondear3.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 70, 60));

        lblNombres.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(0, 0, 0));
        lblNombres.setText("Diego");
        redondear3.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 20));

        lblApellidos.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidos.setText("Bautista");
        redondear3.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, 20));

        lblDNI.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(0, 0, 0));
        lblDNI.setText("DNI:75792854");
        redondear3.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 100, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\informacion (1).png")); // NOI18N
        jLabel5.setText("jLabel5");
        redondear3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 37, -1));

        redondear2.add(redondear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 250, 110));

        redondear1.add(redondear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 650));

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        redondear1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 37, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        redondear1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 37, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(224, 79, 95));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setRoundBottomLeft(60);
        btnCerrarSesion.setRoundBottomRight(60);
        btnCerrarSesion.setRoundTopLeft(60);
        btnCerrarSesion.setRoundTopRight(60);
        btnCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cerrar Sesión");
        btnCerrarSesion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Documents\\GitHub\\ProyectoIntegrador2\\src\\main\\resources\\img\\energia (2).png")); // NOI18N
        btnCerrarSesion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 50));

        redondear1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redondear1, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(redondear1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntHistorialActionPerformed

    private void btnEditorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditorialesActionPerformed

    private void btnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrabajadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaHerramienta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntHistorial;
    public Modelo.Redondear btnCerrarSesion;
    public javax.swing.JButton btnEditoriales;
    public javax.swing.JButton btnInventario;
    public javax.swing.JButton btnTrabajadores;
    public javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JDesktopPane jdpEscritorio;
    public javax.swing.JLabel lblApellidos;
    public javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblDNI;
    public javax.swing.JLabel lblFoto;
    public javax.swing.JLabel lblMinimizar;
    public javax.swing.JLabel lblNombres;
    private Modelo.Redondear redondear1;
    private Modelo.Redondear redondear2;
    private Modelo.Redondear redondear3;
    // End of variables declaration//GEN-END:variables
}
