/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author Frank
 */
public class vistaHerramienta extends javax.swing.JFrame {

    /**
     * Creates new form vistaHerramienta
     */
    public vistaHerramienta() {
         setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        initComponents();
        setLocationRelativeTo(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redondear1 = new Modelo.Redondear();
        jdpEscritorio = new javax.swing.JDesktopPane();
        redondear2 = new Modelo.Redondear();
        jLabel1 = new javax.swing.JLabel();
        btnVentas = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        bntHistorial = new javax.swing.JButton();
        btnEditoriales = new javax.swing.JButton();
        btnTrabajadores = new javax.swing.JButton();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1500, 670));

        redondear1.setBackground(new java.awt.Color(240, 244, 239));
        redondear1.setPreferredSize(new java.awt.Dimension(1500, 660));
        redondear1.setRoundBottomLeft(60);
        redondear1.setRoundBottomRight(60);
        redondear1.setRoundTopLeft(60);
        redondear1.setRoundTopRight(60);
        redondear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdpEscritorio.setBackground(new java.awt.Color(240, 244, 239));
        jdpEscritorio.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        redondear1.add(jdpEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 870, 580));

        redondear2.setBackground(new java.awt.Color(191, 204, 148));
        redondear2.setRoundBottomLeft(60);
        redondear2.setRoundTopLeft(60);
        redondear2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 40)); // NOI18N
        jLabel1.setText("Herramientas");
        redondear2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, 35));

        btnVentas.setBackground(new java.awt.Color(191, 204, 148));
        btnVentas.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setBorder(null);
        redondear2.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 70));

        btnInventario.setBackground(new java.awt.Color(191, 204, 148));
        btnInventario.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setBorder(null);
        redondear2.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 270, 70));

        bntHistorial.setBackground(new java.awt.Color(191, 204, 148));
        bntHistorial.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        bntHistorial.setText("Historial");
        bntHistorial.setBorder(null);
        bntHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntHistorialActionPerformed(evt);
            }
        });
        redondear2.add(bntHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 270, 70));

        btnEditoriales.setBackground(new java.awt.Color(191, 204, 148));
        btnEditoriales.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnEditoriales.setText("Editoriales");
        btnEditoriales.setBorder(null);
        btnEditoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialesActionPerformed(evt);
            }
        });
        redondear2.add(btnEditoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 270, 70));

        btnTrabajadores.setBackground(new java.awt.Color(191, 204, 148));
        btnTrabajadores.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        btnTrabajadores.setText("Trabajadores");
        btnTrabajadores.setBorder(null);
        btnTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajadoresActionPerformed(evt);
            }
        });
        redondear2.add(btnTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 270, 70));

        redondear1.add(redondear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 650));

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        redondear1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 37, -1));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        redondear1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 37, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redondear1, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(redondear1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntHistorialActionPerformed

    private void btnEditorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditorialesActionPerformed

    private void btnTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrabajadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaHerramienta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntHistorial;
    public javax.swing.JButton btnEditoriales;
    public javax.swing.JButton btnInventario;
    public javax.swing.JButton btnTrabajadores;
    public javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JDesktopPane jdpEscritorio;
    public javax.swing.JLabel lblCerrar;
    public javax.swing.JLabel lblMinimizar;
    private Modelo.Redondear redondear1;
    private Modelo.Redondear redondear2;
    // End of variables declaration//GEN-END:variables
}
