/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Frank
 */
public class vistaEditoriales extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaVenta
     */
    public vistaEditoriales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redondear1 = new Modelo.Redondear();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditoriales = new javax.swing.JTable();
        btnEliminar_Edit = new javax.swing.JButton();
        btnActualizar_Edit = new javax.swing.JButton();
        btnAgregar_Edit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombre_editorial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPais_editorial = new javax.swing.JTextField();
        txtEmail_editorial = new javax.swing.JTextField();
        txtTelefono_editorial = new javax.swing.JTextField();
        txtAño_editorial = new javax.swing.JTextField();
        txtId_editorial = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(870, 580));

        redondear1.setBackground(new java.awt.Color(180, 205, 237));
        redondear1.setRoundBottomLeft(60);
        redondear1.setRoundBottomRight(60);
        redondear1.setRoundTopLeft(60);
        redondear1.setRoundTopRight(60);
        redondear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setText("Editoriales");
        redondear1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        tblEditoriales.setBackground(new java.awt.Color(240, 244, 239));
        tblEditoriales.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblEditoriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PAIS", "TELEFONO", "EMAIL", "AÑO"
            }
        ));
        jScrollPane1.setViewportView(tblEditoriales);

        redondear1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 620, 390));

        btnEliminar_Edit.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar_Edit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEliminar_Edit.setText("ELIMINAR ");
        btnEliminar_Edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnEliminar_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_EditActionPerformed(evt);
            }
        });
        redondear1.add(btnEliminar_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 160, 50));

        btnActualizar_Edit.setBackground(new java.awt.Color(51, 153, 255));
        btnActualizar_Edit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnActualizar_Edit.setText("ACTUALIZAR");
        btnActualizar_Edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnActualizar_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar_EditActionPerformed(evt);
            }
        });
        redondear1.add(btnActualizar_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 160, 50));

        btnAgregar_Edit.setBackground(new java.awt.Color(51, 204, 0));
        btnAgregar_Edit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAgregar_Edit.setText("AGREGAR");
        btnAgregar_Edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnAgregar_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_EditActionPerformed(evt);
            }
        });
        redondear1.add(btnAgregar_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 160, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Agregar Nueva Editorial:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        redondear1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, 20));
        redondear1.add(txtNombre_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 100, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("País:");
        redondear1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        redondear1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Teléfono:");
        redondear1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nombre:");
        redondear1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Año:");
        redondear1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("ID:");
        redondear1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        redondear1.add(txtPais_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 100, 20));
        redondear1.add(txtEmail_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 100, 20));
        redondear1.add(txtTelefono_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 100, 20));
        redondear1.add(txtAño_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 100, 20));
        redondear1.add(txtId_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redondear1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redondear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminar_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar_EditActionPerformed

    private void btnActualizar_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar_EditActionPerformed

    private void btnAgregar_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar_EditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar_Edit;
    public javax.swing.JButton btnAgregar_Edit;
    public javax.swing.JButton btnEliminar_Edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.Redondear redondear1;
    public javax.swing.JTable tblEditoriales;
    public javax.swing.JTextField txtAño_editorial;
    public javax.swing.JTextField txtEmail_editorial;
    public javax.swing.JTextField txtId_editorial;
    public javax.swing.JTextField txtNombre_editorial;
    public javax.swing.JTextField txtPais_editorial;
    public javax.swing.JTextField txtTelefono_editorial;
    // End of variables declaration//GEN-END:variables
}
