/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Frank
 */
public class vistaTrabajadores extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaVenta
     */
    public vistaTrabajadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redondear1 = new Modelo.Redondear();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrabajadores = new javax.swing.JTable();
        btnEliminar_Tra = new javax.swing.JButton();
        btnActualizar_Tra = new javax.swing.JButton();
        btnAgregar_Tra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre_trabajadores = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtApellidos_trabajadores = new javax.swing.JTextField();
        txtTelefono_trabajadores = new javax.swing.JTextField();
        txtEmail_trabajadores = new javax.swing.JTextField();
        txtDni_trabajadores = new javax.swing.JTextField();
        txtUsername_trabajadores = new javax.swing.JTextField();
        txtSueldo_trabajadores = new javax.swing.JTextField();
        txtId_trabajadores = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(870, 580));

        redondear1.setBackground(new java.awt.Color(180, 205, 237));
        redondear1.setRoundBottomLeft(60);
        redondear1.setRoundBottomRight(60);
        redondear1.setRoundTopLeft(60);
        redondear1.setRoundTopRight(60);
        redondear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setText("TRABAJADORES");
        redondear1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        tblTrabajadores.setBackground(new java.awt.Color(240, 244, 239));
        tblTrabajadores.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "APELLIDO", "TELEFONO", "EMAIL", "DNI", "USERNAME", "SUELDO"
            }
        ));
        jScrollPane1.setViewportView(tblTrabajadores);

        redondear1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 650, 370));

        btnEliminar_Tra.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar_Tra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEliminar_Tra.setText("ELIMINAR ");
        btnEliminar_Tra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnEliminar_Tra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_TraActionPerformed(evt);
            }
        });
        redondear1.add(btnEliminar_Tra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 160, 50));

        btnActualizar_Tra.setBackground(new java.awt.Color(51, 153, 255));
        btnActualizar_Tra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnActualizar_Tra.setText("Actualizar");
        btnActualizar_Tra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnActualizar_Tra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar_TraActionPerformed(evt);
            }
        });
        redondear1.add(btnActualizar_Tra, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 160, 50));

        btnAgregar_Tra.setBackground(new java.awt.Color(51, 204, 0));
        btnAgregar_Tra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAgregar_Tra.setText("AGREGAR");
        btnAgregar_Tra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnAgregar_Tra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_TraActionPerformed(evt);
            }
        });
        redondear1.add(btnAgregar_Tra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 160, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setText("Agregar Trabajadores:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        redondear1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Username:");
        redondear1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        redondear1.add(txtNombre_trabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 100, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Apellidos:");
        redondear1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Telefono:");
        redondear1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Email:");
        redondear1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("DNI:");
        redondear1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("ID:");
        redondear1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Sueldo:");
        redondear1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Nombres:");
        redondear1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        redondear1.add(txtApellidos_trabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 100, 20));
        redondear1.add(txtTelefono_trabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 100, 20));
        redondear1.add(txtEmail_trabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 100, 20));
        redondear1.add(txtDni_trabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 100, 20));
        redondear1.add(txtUsername_trabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 100, 20));
        redondear1.add(txtSueldo_trabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 100, 20));
        redondear1.add(txtId_trabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redondear1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redondear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminar_TraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_TraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar_TraActionPerformed

    private void btnActualizar_TraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar_TraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizar_TraActionPerformed

    private void btnAgregar_TraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_TraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar_TraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar_Tra;
    public javax.swing.JButton btnAgregar_Tra;
    public javax.swing.JButton btnEliminar_Tra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.Redondear redondear1;
    public javax.swing.JTable tblTrabajadores;
    public javax.swing.JTextField txtApellidos_trabajadores;
    public javax.swing.JTextField txtDni_trabajadores;
    public javax.swing.JTextField txtEmail_trabajadores;
    public javax.swing.JTextField txtId_trabajadores;
    public javax.swing.JTextField txtNombre_trabajadores;
    public javax.swing.JTextField txtSueldo_trabajadores;
    public javax.swing.JTextField txtTelefono_trabajadores;
    public javax.swing.JTextField txtUsername_trabajadores;
    // End of variables declaration//GEN-END:variables
}
