/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Frank
 */
public class vistaInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaInventario
     */
    public vistaInventario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redondear1 = new Modelo.Redondear();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        txtSer = new javax.swing.JTextField();
        cbxEdit = new javax.swing.JComboBox<>();
        cbxRes = new javax.swing.JComboBox<>();
        spnNum = new javax.swing.JSpinner();
        cbxFor = new javax.swing.JComboBox<>();
        spnSto = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        txtUbi = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        txtPre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redondear1.setBackground(new java.awt.Color(180, 205, 237));
        redondear1.setRoundBottomLeft(60);
        redondear1.setRoundBottomRight(60);
        redondear1.setRoundTopLeft(60);
        redondear1.setRoundTopRight(60);
        redondear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Control de Inventario");
        redondear1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        tblInventario.setBackground(new java.awt.Color(240, 244, 239));
        tblInventario.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "EDITORIAL", "SERIE", "UBICACION", "RESTRICCION", "FORMATO", "NUMERO", "STOCK", "PRECIO"
            }
        ));
        jScrollPane1.setViewportView(tblInventario);

        redondear1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 730, 220));

        txtSer.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtSer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SERIE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(txtSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 120, 60));

        cbxEdit.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        cbxEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARVEL", "DC", "IDW" }));
        cbxEdit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EDITORIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(cbxEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, 60));

        cbxRes.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        cbxRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "T", "T+", "M" }));
        cbxRes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESTRICCIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(cbxRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 60));

        spnNum.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        spnNum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NÚMERO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(spnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 120, 60));

        cbxFor.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        cbxFor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tapa Dura", "Tapa Blanda" }));
        cbxFor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORMATO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(cbxFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, 60));

        spnSto.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        spnSto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOCK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(spnSto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 120, 60));

        btnBuscar.setBackground(new java.awt.Color(180, 205, 237));
        btnBuscar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnBuscar.setBorder(null);
        redondear1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 140, 30));

        jComboBox4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        jComboBox4.setBorder(null);
        redondear1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 140, 30));

        txtUbi.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtUbi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UBICACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(txtUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 120, 60));

        btnAgregar.setBackground(new java.awt.Color(51, 204, 0));
        btnAgregar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        redondear1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 120, 40));

        btnActualizar.setBackground(new java.awt.Color(51, 153, 255));
        btnActualizar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        redondear1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 120, 40));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        redondear1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 120, 40));

        btnFiltrar.setBackground(new java.awt.Color(51, 51, 51));
        btnFiltrar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.setBorder(null);
        redondear1.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 90, 30));

        txtPre.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtPre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRECIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(txtPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 120, 60));

        jSeparator1.setBackground(new java.awt.Color(180, 205, 237));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        redondear1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 140, 20));

        getContentPane().add(redondear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JTextField btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnFiltrar;
    public javax.swing.JComboBox<String> cbxEdit;
    public javax.swing.JComboBox<String> cbxFor;
    public javax.swing.JComboBox<String> cbxRes;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private Modelo.Redondear redondear1;
    public javax.swing.JSpinner spnNum;
    public javax.swing.JSpinner spnSto;
    public javax.swing.JTable tblInventario;
    public javax.swing.JTextField txtPre;
    public javax.swing.JTextField txtSer;
    public javax.swing.JTextField txtUbi;
    // End of variables declaration//GEN-END:variables
}
