/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Frank
 */
public class vistaInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaInventario
     */
    public vistaInventario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redondear1 = new Modelo.Redondear();
        jLabel1 = new javax.swing.JLabel();
        btnCerr = new javax.swing.JLabel();
        btnMin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        txtSer = new javax.swing.JTextField();
        cbxEdit = new javax.swing.JComboBox<>();
        cbxRes = new javax.swing.JComboBox<>();
        spnNum = new javax.swing.JSpinner();
        cbxFor = new javax.swing.JComboBox<>();
        spnSto = new javax.swing.JSpinner();
        jTextField3 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        txtUbi = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtPre = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redondear1.setBackground(new java.awt.Color(180, 205, 237));
        redondear1.setRoundBottomLeft(60);
        redondear1.setRoundBottomRight(60);
        redondear1.setRoundTopLeft(60);
        redondear1.setRoundTopRight(60);
        redondear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setText("Control de Inventario");
        redondear1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btnCerr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        redondear1.add(btnCerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        redondear1.add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        tblInventario.setBackground(new java.awt.Color(240, 244, 239));
        tblInventario.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "EDITORIAL", "SERIE", "UBICACION", "RESTRICCION", "FORMATO", "NUMERO", "STOCK", "PRECIO"
            }
        ));
        jScrollPane1.setViewportView(tblInventario);

        redondear1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 730, 220));

        txtSer.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtSer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SERIE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(txtSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 120, 60));

        cbxEdit.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        cbxEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARVEL", "DC", "IDW" }));
        cbxEdit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EDITORIAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(cbxEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 140, -1));

        cbxRes.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        cbxRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "T", "T+", "M" }));
        cbxRes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESTRICCIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(cbxRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, -1));

        spnNum.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        spnNum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NÚMERO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(spnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 120, 60));

        cbxFor.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        cbxFor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tapa Dura", "Tapa Blanda" }));
        cbxFor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORMATO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(cbxFor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        spnSto.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        spnSto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOCK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(spnSto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 120, -1));

        jTextField3.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jTextField3.setBorder(null);
        redondear1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 140, 30));

        jComboBox4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        jComboBox4.setBorder(null);
        redondear1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 140, 30));

        txtUbi.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtUbi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UBICACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(txtUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 120, 60));

        btnAgregar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        redondear1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        btnActualizar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        redondear1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        redondear1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        jButton4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jButton4.setText("BUSCAR");
        jButton4.setBorder(null);
        redondear1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));

        jButton5.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jButton5.setText("FILTRAR");
        jButton5.setBorder(null);
        redondear1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, 20));

        txtPre.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtPre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRECIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        redondear1.add(txtPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 120, 60));

        getContentPane().add(redondear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JLabel btnCerr;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JLabel btnMin;
    public javax.swing.JComboBox<String> cbxEdit;
    public javax.swing.JComboBox<String> cbxFor;
    public javax.swing.JComboBox<String> cbxRes;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private Modelo.Redondear redondear1;
    public javax.swing.JSpinner spnNum;
    public javax.swing.JSpinner spnSto;
    public javax.swing.JTable tblInventario;
    public javax.swing.JTextField txtPre;
    public javax.swing.JTextField txtSer;
    public javax.swing.JTextField txtUbi;
    // End of variables declaration//GEN-END:variables
}
